startdate: "20181215T000000"
enddate: "20181231T235959"
imidir: "/n/holylfs05/LABS/jacob_lab/jeast/integrated_methane_inversion"
workdir: "/n/holylfs05/LABS/jacob_lab/jeast/proj/seasonality/runs/inputs/BC"
gccache: "/n/holylfs05/LABS/jacob_lab/jeast/proj/seasonality/runs/spinup/OutputDir"
tropomi_cache: "/n/holylfs05/LABS/jacob_lab/imi/ch4/blended"
CondaEnv: imi_env2

RunGEOSChem: false
WriteBCs: true
